### Get all questions
GET {{host}}/api/questions


### Get all questions by specified topic
GET {{host}}/api/questions?topic=Maven


### Upload questions
POST {{host}}/api/file/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test_questions.csv"

// the file content to upload
< ../test_questions.csv


### Save new question
POST {{host}}/api/questions
Content-Type: application/json

{
  "topic": "Kotlin",
  "category": {
    "id": 3
  },
  "text": "What is the difference between '.kt' and '.kts' files?"
}


### Get Build Properties (Application Info)
GET {{host}}/api/build-properties


### Get all categories
GET {{host}}/api/categories


### Save Quiz
POST {{host}}/api/quizzes
Content-Type: application/json

{
  "ids": [
    102
  ]
}


### Get Quiz by id
GET {{host}}/api/quizzes/501

