### [ROLE_AUTHOR]: Get all questions
GET {{host-ssl}}/api/questions
Accept: application/json
Authorization: Basic {{base64-basic-author}}


### Get question by id
GET {{host-ssl}}/api/questions/101
Accept: application/json
Authorization: Basic {{base64-basic-user}}


### [ROLE_AUTHOR]: Delete question by id
DELETE {{host-ssl}}/api/questions/102
Accept: application/json
Authorization: Basic {{base64-basic-author}}


### [ROLE_ROOT]: Delete all questions
DELETE {{host-ssl}}/api/questions/all
Accept: application/json
Authorization: Basic {{base64-basic-root}}


### [ROLE_AUTHOR]: Get question's tags
GET {{host}}/api/questions/102/tags
Accept: application/json
Authorization: Basic {{base64-basic-root}}


### Get all questions by specified topic
GET {{host}}/api/questions?topic=Maven
Accept: application/json
Authorization: Basic {{basic-authorization-user}}


### Upload questions
POST {{host}}/api/file/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test_questions.csv"

// the file content to upload
< ../test_questions.csv


### [ROLE_AUTHOR]: Save new question
POST {{host}}/api/questions
Content-Type: application/json
Accept: application/json

{
  "category": {
    "id": 13
  },
  "text": "What is the difference between '.kt' and '.kts' files?"
}


### [ROLE_ROOT]: Get Build Properties (Application Info)
GET {{host-ssl}}/api/build-properties
Accept: application/json
Authorization: Basic {{base64-basic-root}}


### Get all categories
GET {{host}}/api/categories
Accept: application/json
Authorization: Basic YWRtaW5AYm9vc3RpLm9yZzphZG1pbkBib29zdGkub3Jn

### Save Quiz
POST {{host}}/api/quizzes
Content-Type: application/json

{
  "ids": [
    102
  ]
}


### Get Quiz by id
GET {{host}}/api/quizzes/501

